/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 58
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 1
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_source_token1 = 1,
  anon_sym_JJ_COLON = 2,
  aux_sym_comment_token1 = 3,
  aux_sym_subject_token1 = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_BANG = 7,
  aux_sym_prefix_token1 = 8,
  sym_type = 9,
  sym_scope = 10,
  aux_sym_body_line_token1 = 11,
  anon_sym_JJ_COLONignore_DASHrest = 12,
  sym_rest = 13,
  anon_sym_A = 14,
  anon_sym_M = 15,
  anon_sym_D = 16,
  anon_sym_C = 17,
  anon_sym_R = 18,
  aux_sym_generated_comment_token1 = 19,
  sym_change_id = 20,
  sym__change_id = 21,
  sym__diff_summary = 22,
  sym__error_sentinel = 23,
  sym_source = 24,
  sym_comment = 25,
  sym_subject = 26,
  sym_prefix = 27,
  sym_body_line = 28,
  sym_ignore_rest = 29,
  sym_generated_comment = 30,
  sym_filepath = 31,
  aux_sym_source_repeat1 = 32,
  aux_sym_source_repeat2 = 33,
  alias_sym_comment_content = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_source_token1] = "source_token1",
  [anon_sym_JJ_COLON] = "JJ:",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_subject_token1] = "subject_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_BANG] = "!",
  [aux_sym_prefix_token1] = ":",
  [sym_type] = "type",
  [sym_scope] = "scope",
  [aux_sym_body_line_token1] = "body_line_token1",
  [anon_sym_JJ_COLONignore_DASHrest] = "JJ: ignore-rest",
  [sym_rest] = "rest",
  [anon_sym_A] = "A",
  [anon_sym_M] = "M",
  [anon_sym_D] = "D",
  [anon_sym_C] = "C",
  [anon_sym_R] = "R",
  [aux_sym_generated_comment_token1] = "generated_comment_token1",
  [sym_change_id] = "change_id",
  [sym__change_id] = "_change_id",
  [sym__diff_summary] = "_diff_summary",
  [sym__error_sentinel] = "_error_sentinel",
  [sym_source] = "source",
  [sym_comment] = "comment",
  [sym_subject] = "subject",
  [sym_prefix] = "prefix",
  [sym_body_line] = "body_line",
  [sym_ignore_rest] = "ignore_rest",
  [sym_generated_comment] = "generated_comment",
  [sym_filepath] = "filepath",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_source_repeat2] = "source_repeat2",
  [alias_sym_comment_content] = "comment_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_source_token1] = aux_sym_source_token1,
  [anon_sym_JJ_COLON] = anon_sym_JJ_COLON,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_subject_token1] = aux_sym_subject_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_BANG] = anon_sym_BANG,
  [aux_sym_prefix_token1] = aux_sym_prefix_token1,
  [sym_type] = sym_type,
  [sym_scope] = sym_scope,
  [aux_sym_body_line_token1] = aux_sym_body_line_token1,
  [anon_sym_JJ_COLONignore_DASHrest] = anon_sym_JJ_COLONignore_DASHrest,
  [sym_rest] = sym_rest,
  [anon_sym_A] = anon_sym_A,
  [anon_sym_M] = anon_sym_M,
  [anon_sym_D] = anon_sym_D,
  [anon_sym_C] = anon_sym_C,
  [anon_sym_R] = anon_sym_R,
  [aux_sym_generated_comment_token1] = aux_sym_generated_comment_token1,
  [sym_change_id] = sym_change_id,
  [sym__change_id] = sym__change_id,
  [sym__diff_summary] = sym__diff_summary,
  [sym__error_sentinel] = sym__error_sentinel,
  [sym_source] = sym_source,
  [sym_comment] = sym_comment,
  [sym_subject] = sym_subject,
  [sym_prefix] = sym_prefix,
  [sym_body_line] = sym_body_line,
  [sym_ignore_rest] = sym_ignore_rest,
  [sym_generated_comment] = sym_generated_comment,
  [sym_filepath] = sym_filepath,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_source_repeat2] = aux_sym_source_repeat2,
  [alias_sym_comment_content] = alias_sym_comment_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_JJ_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subject_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_prefix_token1] = {
    .visible = true,
    .named = false,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_body_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_JJ_COLONignore_DASHrest] = {
    .visible = true,
    .named = false,
  },
  [sym_rest] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_A] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_M] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_D] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_C] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_R] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_generated_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_change_id] = {
    .visible = true,
    .named = true,
  },
  [sym__change_id] = {
    .visible = false,
    .named = true,
  },
  [sym__diff_summary] = {
    .visible = false,
    .named = true,
  },
  [sym__error_sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_body_line] = {
    .visible = true,
    .named = true,
  },
  [sym_ignore_rest] = {
    .visible = true,
    .named = true,
  },
  [sym_generated_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_filepath] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_repeat2] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_comment_content] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_comment_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 12,
  [19] = 11,
  [20] = 9,
  [21] = 10,
  [22] = 22,
  [23] = 22,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 28,
  [34] = 34,
  [35] = 27,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 36,
  [49] = 49,
  [50] = 50,
  [51] = 45,
  [52] = 52,
  [53] = 39,
  [54] = 54,
  [55] = 55,
  [56] = 42,
  [57] = 54,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '\n', 22,
        '\r', 1,
        ' ', 53,
        '!', 28,
        '(', 26,
        ')', 27,
        'A', 44,
        'C', 50,
        'D', 48,
        'J', 34,
        'M', 46,
        'R', 52,
        ':', 29,
        0xff1a, 29,
      );
      if (('k' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'j')) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(25);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '(' &&
          lookahead != ':' &&
          lookahead != 0xff1a) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(43);
      if (lookahead == 'C') ADVANCE(49);
      if (lookahead == 'D') ADVANCE(47);
      if (lookahead == 'M') ADVANCE(45);
      if (lookahead == 'R') ADVANCE(51);
      if (('k' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'g') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ')') ADVANCE(37);
      END_STATE();
    case 18:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'J') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead) &&
          lookahead != 0xff1a) ADVANCE(4);
      END_STATE();
    case 19:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'J') ADVANCE(39);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_source_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_JJ_COLON);
      if (lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_subject_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_prefix_token1);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_type);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == ':') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '(' &&
          lookahead != 0xff1a) ADVANCE(4);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_type);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'J') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead) &&
          lookahead != 0xff1a) ADVANCE(4);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_type);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead) &&
          lookahead != 0xff1a) ADVANCE(4);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_type);
      if (lookahead == ':') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_type);
      if (lookahead == 'J') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_type);
      if (('k' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'j')) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_scope);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ')') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_body_line_token1);
      if (lookahead == ':') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_body_line_token1);
      if (lookahead == 'J') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_body_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_JJ_COLONignore_DASHrest);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_rest);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_A);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_A);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_M);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_M);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_D);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_D);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_C);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_C);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_R);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_R);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_generated_comment_token1);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_change_id);
      if (('k' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 18, .external_lex_state = 2},
  [2] = {.lex_state = 18, .external_lex_state = 2},
  [3] = {.lex_state = 19, .external_lex_state = 2},
  [4] = {.lex_state = 19, .external_lex_state = 2},
  [5] = {.lex_state = 19, .external_lex_state = 2},
  [6] = {.lex_state = 19, .external_lex_state = 2},
  [7] = {.lex_state = 18, .external_lex_state = 2},
  [8] = {.lex_state = 19, .external_lex_state = 2},
  [9] = {.lex_state = 18, .external_lex_state = 2},
  [10] = {.lex_state = 18, .external_lex_state = 2},
  [11] = {.lex_state = 18, .external_lex_state = 2},
  [12] = {.lex_state = 18, .external_lex_state = 2},
  [13] = {.lex_state = 19, .external_lex_state = 2},
  [14] = {.lex_state = 19, .external_lex_state = 2},
  [15] = {.lex_state = 19, .external_lex_state = 2},
  [16] = {.lex_state = 19, .external_lex_state = 2},
  [17] = {.lex_state = 19, .external_lex_state = 2},
  [18] = {.lex_state = 19, .external_lex_state = 2},
  [19] = {.lex_state = 19, .external_lex_state = 2},
  [20] = {.lex_state = 19, .external_lex_state = 2},
  [21] = {.lex_state = 19, .external_lex_state = 2},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 20},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 17},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_source_token1] = ACTIONS(1),
    [anon_sym_JJ_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [aux_sym_prefix_token1] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
    [anon_sym_JJ_COLONignore_DASHrest] = ACTIONS(1),
    [anon_sym_A] = ACTIONS(1),
    [anon_sym_M] = ACTIONS(1),
    [anon_sym_D] = ACTIONS(1),
    [anon_sym_C] = ACTIONS(1),
    [anon_sym_R] = ACTIONS(1),
    [aux_sym_generated_comment_token1] = ACTIONS(1),
    [sym_change_id] = ACTIONS(1),
    [sym__change_id] = ACTIONS(1),
    [sym__diff_summary] = ACTIONS(1),
    [sym__error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(52),
    [sym_comment] = STATE(2),
    [sym_subject] = STATE(4),
    [sym_prefix] = STATE(34),
    [sym_ignore_rest] = STATE(37),
    [sym_generated_comment] = STATE(2),
    [aux_sym_source_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_source_token1] = ACTIONS(5),
    [anon_sym_JJ_COLON] = ACTIONS(7),
    [aux_sym_subject_token1] = ACTIONS(9),
    [sym_type] = ACTIONS(11),
    [anon_sym_JJ_COLONignore_DASHrest] = ACTIONS(13),
    [sym__change_id] = ACTIONS(15),
    [sym__diff_summary] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(7), 1,
      anon_sym_JJ_COLON,
    ACTIONS(9), 1,
      aux_sym_subject_token1,
    ACTIONS(11), 1,
      sym_type,
    ACTIONS(13), 1,
      anon_sym_JJ_COLONignore_DASHrest,
    ACTIONS(15), 1,
      sym__change_id,
    ACTIONS(17), 1,
      sym__diff_summary,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      aux_sym_source_token1,
    STATE(5), 1,
      sym_subject,
    STATE(34), 1,
      sym_prefix,
    STATE(46), 1,
      sym_ignore_rest,
    STATE(7), 3,
      sym_comment,
      sym_generated_comment,
      aux_sym_source_repeat1,
  [39] = 9,
    ACTIONS(13), 1,
      anon_sym_JJ_COLONignore_DASHrest,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      aux_sym_source_token1,
    ACTIONS(27), 1,
      anon_sym_JJ_COLON,
    ACTIONS(29), 1,
      aux_sym_body_line_token1,
    ACTIONS(31), 1,
      sym__change_id,
    ACTIONS(33), 1,
      sym__diff_summary,
    STATE(50), 1,
      sym_ignore_rest,
    STATE(8), 4,
      sym_comment,
      sym_body_line,
      sym_generated_comment,
      aux_sym_source_repeat2,
  [70] = 9,
    ACTIONS(13), 1,
      anon_sym_JJ_COLONignore_DASHrest,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_JJ_COLON,
    ACTIONS(29), 1,
      aux_sym_body_line_token1,
    ACTIONS(31), 1,
      sym__change_id,
    ACTIONS(33), 1,
      sym__diff_summary,
    ACTIONS(35), 1,
      aux_sym_source_token1,
    STATE(46), 1,
      sym_ignore_rest,
    STATE(3), 4,
      sym_comment,
      sym_body_line,
      sym_generated_comment,
      aux_sym_source_repeat2,
  [101] = 9,
    ACTIONS(13), 1,
      anon_sym_JJ_COLONignore_DASHrest,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_JJ_COLON,
    ACTIONS(29), 1,
      aux_sym_body_line_token1,
    ACTIONS(31), 1,
      sym__change_id,
    ACTIONS(33), 1,
      sym__diff_summary,
    ACTIONS(37), 1,
      aux_sym_source_token1,
    STATE(50), 1,
      sym_ignore_rest,
    STATE(6), 4,
      sym_comment,
      sym_body_line,
      sym_generated_comment,
      aux_sym_source_repeat2,
  [132] = 9,
    ACTIONS(13), 1,
      anon_sym_JJ_COLONignore_DASHrest,
    ACTIONS(25), 1,
      aux_sym_source_token1,
    ACTIONS(27), 1,
      anon_sym_JJ_COLON,
    ACTIONS(29), 1,
      aux_sym_body_line_token1,
    ACTIONS(31), 1,
      sym__change_id,
    ACTIONS(33), 1,
      sym__diff_summary,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    STATE(41), 1,
      sym_ignore_rest,
    STATE(8), 4,
      sym_comment,
      sym_body_line,
      sym_generated_comment,
      aux_sym_source_repeat2,
  [163] = 7,
    ACTIONS(43), 1,
      aux_sym_source_token1,
    ACTIONS(46), 1,
      anon_sym_JJ_COLON,
    ACTIONS(49), 1,
      sym_type,
    ACTIONS(51), 1,
      sym__change_id,
    ACTIONS(54), 1,
      sym__diff_summary,
    ACTIONS(41), 3,
      ts_builtin_sym_end,
      aux_sym_subject_token1,
      anon_sym_JJ_COLONignore_DASHrest,
    STATE(7), 3,
      sym_comment,
      sym_generated_comment,
      aux_sym_source_repeat1,
  [189] = 7,
    ACTIONS(59), 1,
      aux_sym_source_token1,
    ACTIONS(62), 1,
      anon_sym_JJ_COLON,
    ACTIONS(65), 1,
      aux_sym_body_line_token1,
    ACTIONS(68), 1,
      sym__change_id,
    ACTIONS(71), 1,
      sym__diff_summary,
    ACTIONS(57), 2,
      ts_builtin_sym_end,
      anon_sym_JJ_COLONignore_DASHrest,
    STATE(8), 4,
      sym_comment,
      sym_body_line,
      sym_generated_comment,
      aux_sym_source_repeat2,
  [215] = 2,
    ACTIONS(76), 2,
      anon_sym_JJ_COLON,
      sym_type,
    ACTIONS(74), 6,
      sym__change_id,
      sym__diff_summary,
      ts_builtin_sym_end,
      aux_sym_source_token1,
      aux_sym_subject_token1,
      anon_sym_JJ_COLONignore_DASHrest,
  [228] = 2,
    ACTIONS(80), 2,
      anon_sym_JJ_COLON,
      sym_type,
    ACTIONS(78), 6,
      sym__change_id,
      sym__diff_summary,
      ts_builtin_sym_end,
      aux_sym_source_token1,
      aux_sym_subject_token1,
      anon_sym_JJ_COLONignore_DASHrest,
  [241] = 2,
    ACTIONS(84), 2,
      anon_sym_JJ_COLON,
      sym_type,
    ACTIONS(82), 6,
      sym__change_id,
      sym__diff_summary,
      ts_builtin_sym_end,
      aux_sym_source_token1,
      aux_sym_subject_token1,
      anon_sym_JJ_COLONignore_DASHrest,
  [254] = 2,
    ACTIONS(88), 2,
      anon_sym_JJ_COLON,
      sym_type,
    ACTIONS(86), 6,
      sym__change_id,
      sym__diff_summary,
      ts_builtin_sym_end,
      aux_sym_source_token1,
      aux_sym_subject_token1,
      anon_sym_JJ_COLONignore_DASHrest,
  [267] = 2,
    ACTIONS(92), 2,
      anon_sym_JJ_COLON,
      aux_sym_body_line_token1,
    ACTIONS(90), 5,
      sym__change_id,
      sym__diff_summary,
      ts_builtin_sym_end,
      aux_sym_source_token1,
      anon_sym_JJ_COLONignore_DASHrest,
  [279] = 2,
    ACTIONS(96), 2,
      anon_sym_JJ_COLON,
      aux_sym_body_line_token1,
    ACTIONS(94), 5,
      sym__change_id,
      sym__diff_summary,
      ts_builtin_sym_end,
      aux_sym_source_token1,
      anon_sym_JJ_COLONignore_DASHrest,
  [291] = 3,
    ACTIONS(100), 1,
      aux_sym_source_token1,
    ACTIONS(102), 2,
      anon_sym_JJ_COLON,
      aux_sym_body_line_token1,
    ACTIONS(98), 4,
      sym__change_id,
      sym__diff_summary,
      ts_builtin_sym_end,
      anon_sym_JJ_COLONignore_DASHrest,
  [305] = 2,
    ACTIONS(106), 2,
      anon_sym_JJ_COLON,
      aux_sym_body_line_token1,
    ACTIONS(104), 5,
      sym__change_id,
      sym__diff_summary,
      ts_builtin_sym_end,
      aux_sym_source_token1,
      anon_sym_JJ_COLONignore_DASHrest,
  [317] = 2,
    ACTIONS(110), 2,
      anon_sym_JJ_COLON,
      aux_sym_body_line_token1,
    ACTIONS(108), 5,
      sym__change_id,
      sym__diff_summary,
      ts_builtin_sym_end,
      aux_sym_source_token1,
      anon_sym_JJ_COLONignore_DASHrest,
  [329] = 2,
    ACTIONS(88), 2,
      anon_sym_JJ_COLON,
      aux_sym_body_line_token1,
    ACTIONS(86), 5,
      sym__change_id,
      sym__diff_summary,
      ts_builtin_sym_end,
      aux_sym_source_token1,
      anon_sym_JJ_COLONignore_DASHrest,
  [341] = 2,
    ACTIONS(84), 2,
      anon_sym_JJ_COLON,
      aux_sym_body_line_token1,
    ACTIONS(82), 5,
      sym__change_id,
      sym__diff_summary,
      ts_builtin_sym_end,
      aux_sym_source_token1,
      anon_sym_JJ_COLONignore_DASHrest,
  [353] = 2,
    ACTIONS(76), 2,
      anon_sym_JJ_COLON,
      aux_sym_body_line_token1,
    ACTIONS(74), 5,
      sym__change_id,
      sym__diff_summary,
      ts_builtin_sym_end,
      aux_sym_source_token1,
      anon_sym_JJ_COLONignore_DASHrest,
  [365] = 2,
    ACTIONS(80), 2,
      anon_sym_JJ_COLON,
      aux_sym_body_line_token1,
    ACTIONS(78), 5,
      sym__change_id,
      sym__diff_summary,
      ts_builtin_sym_end,
      aux_sym_source_token1,
      anon_sym_JJ_COLONignore_DASHrest,
  [377] = 1,
    ACTIONS(112), 5,
      anon_sym_A,
      anon_sym_M,
      anon_sym_D,
      anon_sym_C,
      anon_sym_R,
  [385] = 1,
    ACTIONS(114), 5,
      anon_sym_A,
      anon_sym_M,
      anon_sym_D,
      anon_sym_C,
      anon_sym_R,
  [393] = 3,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(118), 1,
      anon_sym_BANG,
    ACTIONS(120), 1,
      aux_sym_prefix_token1,
  [403] = 1,
    ACTIONS(122), 2,
      aux_sym_source_token1,
      aux_sym_comment_token1,
  [408] = 2,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    ACTIONS(126), 1,
      sym_rest,
  [415] = 2,
    ACTIONS(128), 1,
      aux_sym_comment_token1,
    STATE(39), 1,
      sym_filepath,
  [422] = 2,
    ACTIONS(130), 1,
      aux_sym_source_token1,
    ACTIONS(132), 1,
      aux_sym_comment_token1,
  [429] = 1,
    ACTIONS(134), 2,
      aux_sym_source_token1,
      aux_sym_comment_token1,
  [434] = 1,
    ACTIONS(136), 2,
      aux_sym_source_token1,
      aux_sym_comment_token1,
  [439] = 1,
    ACTIONS(138), 2,
      aux_sym_source_token1,
      aux_sym_comment_token1,
  [444] = 2,
    ACTIONS(140), 1,
      anon_sym_BANG,
    ACTIONS(142), 1,
      aux_sym_prefix_token1,
  [451] = 2,
    ACTIONS(144), 1,
      aux_sym_source_token1,
    ACTIONS(146), 1,
      aux_sym_comment_token1,
  [458] = 2,
    ACTIONS(148), 1,
      aux_sym_source_token1,
    ACTIONS(150), 1,
      aux_sym_comment_token1,
  [465] = 2,
    ACTIONS(128), 1,
      aux_sym_comment_token1,
    STATE(53), 1,
      sym_filepath,
  [472] = 1,
    ACTIONS(152), 1,
      aux_sym_source_token1,
  [476] = 1,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
  [480] = 1,
    ACTIONS(154), 1,
      aux_sym_source_token1,
  [484] = 1,
    ACTIONS(156), 1,
      aux_sym_source_token1,
  [488] = 1,
    ACTIONS(158), 1,
      aux_sym_prefix_token1,
  [492] = 1,
    ACTIONS(160), 1,
      ts_builtin_sym_end,
  [496] = 1,
    ACTIONS(162), 1,
      aux_sym_generated_comment_token1,
  [500] = 1,
    ACTIONS(164), 1,
      aux_sym_prefix_token1,
  [504] = 1,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
  [508] = 1,
    ACTIONS(168), 1,
      aux_sym_source_token1,
  [512] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
  [516] = 1,
    ACTIONS(170), 1,
      anon_sym_RPAREN,
  [520] = 1,
    ACTIONS(172), 1,
      aux_sym_source_token1,
  [524] = 1,
    ACTIONS(174), 1,
      sym_scope,
  [528] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
  [532] = 1,
    ACTIONS(176), 1,
      aux_sym_source_token1,
  [536] = 1,
    ACTIONS(178), 1,
      ts_builtin_sym_end,
  [540] = 1,
    ACTIONS(180), 1,
      aux_sym_source_token1,
  [544] = 1,
    ACTIONS(182), 1,
      sym_change_id,
  [548] = 1,
    ACTIONS(184), 1,
      aux_sym_source_token1,
  [552] = 1,
    ACTIONS(186), 1,
      aux_sym_generated_comment_token1,
  [556] = 1,
    ACTIONS(188), 1,
      sym_change_id,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 101,
  [SMALL_STATE(6)] = 132,
  [SMALL_STATE(7)] = 163,
  [SMALL_STATE(8)] = 189,
  [SMALL_STATE(9)] = 215,
  [SMALL_STATE(10)] = 228,
  [SMALL_STATE(11)] = 241,
  [SMALL_STATE(12)] = 254,
  [SMALL_STATE(13)] = 267,
  [SMALL_STATE(14)] = 279,
  [SMALL_STATE(15)] = 291,
  [SMALL_STATE(16)] = 305,
  [SMALL_STATE(17)] = 317,
  [SMALL_STATE(18)] = 329,
  [SMALL_STATE(19)] = 341,
  [SMALL_STATE(20)] = 353,
  [SMALL_STATE(21)] = 365,
  [SMALL_STATE(22)] = 377,
  [SMALL_STATE(23)] = 385,
  [SMALL_STATE(24)] = 393,
  [SMALL_STATE(25)] = 403,
  [SMALL_STATE(26)] = 408,
  [SMALL_STATE(27)] = 415,
  [SMALL_STATE(28)] = 422,
  [SMALL_STATE(29)] = 429,
  [SMALL_STATE(30)] = 434,
  [SMALL_STATE(31)] = 439,
  [SMALL_STATE(32)] = 444,
  [SMALL_STATE(33)] = 451,
  [SMALL_STATE(34)] = 458,
  [SMALL_STATE(35)] = 465,
  [SMALL_STATE(36)] = 472,
  [SMALL_STATE(37)] = 476,
  [SMALL_STATE(38)] = 480,
  [SMALL_STATE(39)] = 484,
  [SMALL_STATE(40)] = 488,
  [SMALL_STATE(41)] = 492,
  [SMALL_STATE(42)] = 496,
  [SMALL_STATE(43)] = 500,
  [SMALL_STATE(44)] = 504,
  [SMALL_STATE(45)] = 508,
  [SMALL_STATE(46)] = 512,
  [SMALL_STATE(47)] = 516,
  [SMALL_STATE(48)] = 520,
  [SMALL_STATE(49)] = 524,
  [SMALL_STATE(50)] = 528,
  [SMALL_STATE(51)] = 532,
  [SMALL_STATE(52)] = 536,
  [SMALL_STATE(53)] = 540,
  [SMALL_STATE(54)] = 544,
  [SMALL_STATE(55)] = 548,
  [SMALL_STATE(56)] = 552,
  [SMALL_STATE(57)] = 556,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat2, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat2, 2, 0, 0), SHIFT_REPEAT(8),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat2, 2, 0, 0), SHIFT_REPEAT(33),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat2, 2, 0, 0), SHIFT_REPEAT(15),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat2, 2, 0, 0), SHIFT_REPEAT(54),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat2, 2, 0, 0), SHIFT_REPEAT(22),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generated_comment, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_generated_comment, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 1),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 1),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generated_comment, 5, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_generated_comment, 5, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subject, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subject, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_line, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_line, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_line, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_line, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subject, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ignore_rest, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix, 6, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix, 5, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filepath, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 4, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ignore_rest, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [178] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__change_id = 0,
  ts_external_token__diff_summary = 1,
  ts_external_token__error_sentinel = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__change_id] = sym__change_id,
  [ts_external_token__diff_summary] = sym__diff_summary,
  [ts_external_token__error_sentinel] = sym__error_sentinel,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__change_id] = true,
    [ts_external_token__diff_summary] = true,
    [ts_external_token__error_sentinel] = true,
  },
  [2] = {
    [ts_external_token__change_id] = true,
    [ts_external_token__diff_summary] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_jjdescription_external_scanner_create(void);
void tree_sitter_jjdescription_external_scanner_destroy(void *);
bool tree_sitter_jjdescription_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_jjdescription_external_scanner_serialize(void *, char *);
void tree_sitter_jjdescription_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jjdescription(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_jjdescription_external_scanner_create,
      tree_sitter_jjdescription_external_scanner_destroy,
      tree_sitter_jjdescription_external_scanner_scan,
      tree_sitter_jjdescription_external_scanner_serialize,
      tree_sitter_jjdescription_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "jjdescription",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
